/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearChat' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllProfilesByEmail' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
  });
  
  return IDL.Service({
    'clearChat' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllProfilesByEmail' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };